spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root!@#$123
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka